management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
    tags:
      application: sandbox

  prometheus:
    metrics:
      export:
        enabled: true